[package]
name = "merkle_verify"
type = "lib"
authors = [""]

[dependencies]
trees = { git = "https://github.com/privacy-scaling-explorations/zk-kit.noir", tag = "main", directory = "packages/merkle-trees" }
constants = { path = "../constants" }
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v0.85.0", directory="noir-projects/aztec-nr/aztec" }
poseidon = { tag = "v0.1.0", git = "https://github.com/noir-lang/poseidon" }